
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import Link from "next/link";

export default function PrivacyPolicyPage() {
  return (
    <main className="flex min-h-screen flex-col items-center p-4 md:p-8 bg-background">
      <Card className="w-full max-w-4xl">
        <CardHeader>
          <CardTitle>Privacy Policy</CardTitle>
          <CardDescription>Last updated: {new Date().toLocaleDateString()}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6 prose prose-neutral dark:prose-invert max-w-none">
          <p>
            GenoUI ("us", "we", or "our") operates the genoui.vercel.app website (the "Service"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
          </p>

          <section>
            <h2 className="text-xl font-semibold">1. Information Collection and Use</h2>
            <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
            <h3 className="font-semibold">Types of Data Collected</h3>
            <ul>
              <li><strong>Personal Data:</strong> While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). This may include your email address and name when you create an account via services like Google or directly.</li>
              <li><strong>Usage Data & Prompts:</strong> We collect the prompts you enter and the UI components generated by the Service. This data is used to improve our AI models and the overall quality of the service. This may include your IP address, browser type, and other diagnostic data.</li>
              <li><strong>Cookies Data:</strong> We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold">2. Use of Data</h2>
            <p>GenoUI uses the collected data for various purposes:</p>
            <ul>
              <li>To provide and maintain our Service.</li>
              <li>To manage your account and provide you with customer support.</li>
              <li>To monitor the usage of our Service.</li>
              <li>To detect, prevent and address technical issues.</li>
              <li>To improve the accuracy and capabilities of our AI models. Prompts and generated components may be used as training data. We will not use Personal Data for model training.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold">3. Data Storage and Security</h2>
            <p>
              Your information, including Personal Data, is processed and stored using secure services like Firebase. The security of your data is important to us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure.
            </p>
          </section>
          
          <section>
            <h2 className="text-xl font-semibold">4. Community Features</h2>
            <p>
              If you choose to publish a component to the community gallery, the component's name, description, prompt, and generated code will be publicly visible. Your username may be associated with your published components.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">5. Your Data Rights</h2>
            <p>
              You have the right to access, update, or delete the information we have on you. If you wish to delete your account and associated data, please contact us.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">6. Changes to This Privacy Policy</h2>
            <p>
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, please contact us.</p>
          </section>

        </CardContent>
      </Card>
    </main>
  );
}
