
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import Link from "next/link";

export default function TermsOfServicePage() {
  return (
    <main className="flex min-h-screen flex-col items-center p-4 md:p-8 bg-background">
      <Card className="w-full max-w-4xl">
        <CardHeader>
          <CardTitle>Terms and Conditions</CardTitle>
          <CardDescription>Last updated: {new Date().toLocaleDateString()}</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6 prose prose-neutral dark:prose-invert max-w-none">
          <p>
            Welcome to GenoUI! These terms and conditions outline the rules and regulations for the use of GenoUI's Website, located at genoui.vercel.app. By accessing this website we assume you accept these terms and conditions. Do not continue to use GenoUI if you do not agree to all of the terms and conditions stated on this page.
          </p>

          <section>
            <h2 className="text-xl font-semibold">1. Accounts</h2>
            <p>
              When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">2. User-Generated Content</h2>
            <p>
              Our Service allows you to create, generate, and publish UI components ("Content"). You are responsible for the Content that you generate and publish on or through the Service, including its legality, reliability, and appropriateness. By publishing Content on the Service, you grant us the right and license to use, modify, publicly display, and distribute such Content on and through the Service for the purpose of operating and providing the Service to you and to our other users.
            </p>
            <p>
              You retain any and all of your rights to any Content you submit, post or display on or through the Service and you are responsible for protecting those rights. You agree that this license includes the right for us to make your Content available to other users of the Service, who may also use your Content subject to these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">3. Intellectual Property Rights</h2>
            <p>
              The code and components generated by the GenoUI AI are provided to you for your use. While you are free to use, modify, and incorporate the generated code into your projects (commercial or non-commercial), GenoUI does not claim ownership over the generated output. You are responsible for ensuring that your use of the generated code does not infringe on any third-party rights. The Service itself, including all original features, content, and functionality, is and will remain the exclusive property of GenoUI and its licensors.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">4. Acceptable Use</h2>
            <p>
              You agree not to use the Service for any purpose that is illegal or prohibited by these Terms. You may not use the Service in any manner that could damage, disable, overburden, or impair the Service. You agree not to generate content that is defamatory, obscene, pornographic, vulgar, or offensive.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">5. Termination</h2>
            <p>
              We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">6. Disclaimer of Warranty</h2>
            <p>
              The Service is provided on an "AS IS" and "AS AVAILABLE" basis. GenoUI makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. The code generated by the AI is for guidance and assistance only; you are solely responsible for testing, validating, and ensuring the security and quality of any code you use in a production environment.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">7. Limitation of Liability</h2>
            <p>
              In no event shall GenoUI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">8. Changes to Terms</h2>
            <p>
              We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold">Contact Us</h2>
            <p>If you have any questions about these Terms, please contact us.</p>
          </section>

        </CardContent>
      </Card>
    </main>
  );
}
